const GET_USERS_SAGA = 'GET_USERS_SAGA';
const SET_USERS = 'SET_USERS';
const GET_NEW_DECK = 'GET_NEW_DECK';
const SET_NEW_DECK = 'SET_NEW_DECK';
const DRAW_CARDS_FROM_DECK = 'DRAW_CARDS_FROM_DECK';
const SET_REQUEST_TOKEN = 'SET_REQUEST_TOKEN';
const SET_DEAL_CARDS = 'SET_DEAL_CARDS;'
const SET_GAME_STATUS = 'SET_GAME_STATUS;'
const RESET_GAME = 'RESET_GAME;'
const CHANGE_CARD_DISPLAY = 'CHANGE_CARD_DISPLAY;'

export {  //eslint-disable-line
  GET_USERS_SAGA,
  SET_USERS,
  GET_NEW_DECK,
  SET_NEW_DECK,
  SET_DEAL_CARDS,
  SET_REQUEST_TOKEN,
  DRAW_CARDS_FROM_DECK,
  SET_GAME_STATUS,
  RESET_GAME,
  CHANGE_CARD_DISPLAY
};
